from typing import Protocol, Callable

class ViewInterface(Protocol):
    def close_window(self) -> None: ...
    def show_dialog_confirmation(self, message: str, action: Callable[[], None], confirm_action: str = "exit") -> bool: ...
    def show_dialog_results(self, message: str, confirm_action: str, res: int) -> None: ...
    def create_new_session_widget(self, name_spot: str, value_pack: bool, market_tax: float, extra_profit: bool, spot_id_icon: str, no_market_items: list[str], items: dict[str, tuple[str, int]], elixirs_cost: str) -> None: ...
    def update_exchange_hides_results(self, exchange_results: tuple[int, int, int]) -> None: ...
    def set_ui_enabled(self, enabled: bool) -> None: ...
    def set_session_button_enabled(self, enabled: bool) -> None: ...
    def show_dialog_error(self, msg: str) -> None: ...
    def create_settings_widget(self) -> None: ...