from PySide6.QtWidgets import QMainWindow
from typing import Protocol

from config.config import FlatDict

class ViewInterface(Protocol):
    def close_window(self) -> None: ...
    def create_new_session_widget(self, name_spot: str, value_pack: bool, auto_calculate_best_profit: bool, market_tax: float, extra_profit: bool, spot_id_icon: str, no_market_items: list[str], items: FlatDict, elixirs_cost: str,
                                  lightstone_costs: FlatDict, imperfect_lightstone_costs: FlatDict) -> None: ...
    def update_exchange_hides_results(self, exchange_results: tuple[int, int, int]) -> None: ...
    def set_ui_enabled(self, enabled: bool) -> None: ...
    def set_session_button_enabled(self, enabled: bool) -> None: ...
    def create_settings_widget(self) -> None: ...
    def get_main_window_instance(self) -> QMainWindow: ...
    def change_page(self, page: str) -> None: ...
    def get_current_page_name(self) -> str | None: ...
    def process_view_session(self, session_file_selected: str) -> None: ...