from typing import Protocol, Optional

from logic.data_classes.new_session_data import NewSessionData

class ViewInterface(Protocol):
    def close_window(self) -> None: ...
    def create_new_session_widget(self, new_session: NewSessionData) -> None: ...
    def set_ui_enabled(self, enabled: bool) -> None: ...
    def set_session_button_enabled(self, enabled: bool) -> None: ...
    def create_settings_widget(self) -> None: ...
    def change_page(self, page: str) -> None: ...
    def get_current_page_name(self) -> Optional[str]: ...
    def process_view_session(self, session_file_selected: str) -> None: ...