from typing import Protocol, Callable

class ViewInterface(Protocol):
    def close_window(self) -> None: ...
    def show_dialog_confirmation(self, message: str, action: Callable[[], None], confirm_action: str = "exit") -> bool: ...
    def show_dialog_results(self, message: str, confirm_action: str = "clean_results") -> None: ...
    def create_new_session_widget(self, name_spot: str, id_icon:str,  no_market_items: list[str], prices: list[tuple[str, int]], elixir_costs: list[tuple[str, int]]) -> None: ...
    def update_exchange_results(self, exchange_results: tuple[int, int, int]) -> None: ...
    def set_ui_enabled(self, enabled: bool) -> None: ...
    def show_dialog_error(self, msg: str) -> None: ...